/** @type {import('@remix-run/dev').AppConfig} */

module.exports = {
    future: {
        // v2_routeConvention: true,
        // v2_dev: true,
    },
    serverDependenciesToBundle: [
        "chartjs-adapter-date-fns",
        "chartjs-chart-treemap",
        "remix-utils/client-only",
        "@nivo/core",
        "@nivo/treemap"
    ],
    // ignoredRouteFiles: [".*"],
    serverModuleFormat: "cjs",
    // serverModuleFormat: "esm",
    // browserNodeBuiltinsPolyfill: {
    //   modules: builtinModules,
    // },
    // serverNodeBuiltinsPolyfill: {
    //     modules: {
    // _stream_duplex: true,
    // _stream_passthrough: true,
    // _stream_readable: true,
    // _stream_transform: true,
    // _stream_writable: true,
    // assert: true,
    // "assert/strict": true,
    // buffer: true,
    // console: true,
    // constants: true,
    // crypto: "empty",
    // diagnostics_channel: true,
    // domain: true,
    // events: true,
    // fs: "empty",
    // "fs/promises": "empty",
    // http: true,
    // https: true,
    // module: true,
    // os: true,
    // path: true,
    // "path/posix": true,
    // "path/win32": true,
    // perf_hooks: true,
    // process: true,
    // punycode: true,
    // querystring: true,
    // stream: true,
    // "stream/promises": true,
    // "stream/web": true,
    // string_decoder: true,
    // sys: true,
    // timers: true,
    // "timers/promises": true,
    // tty: true,
    // url: true,
    // util: true,
    // "util/types": true,
    // vm: true,
    // wasi: true,
    // worker_threads: true,
    // zlib: true,
    //   },
    // },
};
